### ISSUE TITLE
Please make the code private

### ISSUE THREAD

**Issue by dontpingmem8** [NoNameGivenCoder/Sapphire#10]
I know you probably don't wanna hear from me but it would be best if you made the code private so people stop trying to rehost it

**Comment by PokeyManatee4** [comment]
If not, can I still rehost after the nights and hours I've put into this project

**Comment by NoNameGivenCoder** [comment]
Nope!!!! 😋 If people are smart enough to rehost this, I give them credit where credits due. My work will always be open source for people to learn with and expand on. I never want to make this code closed source, that's just boring. 

If people want to fork this, expand and create more, I applaud them. For the people just rehosting this for fun, good job, you just rehosted something!! Now go learn Node.JS. Now please forget this ever happened and move on with your day!!

**Comment by davidsosa2022** [comment]
12121212122 rehosts incoming

**Comment by SomeonesGarbage** [comment]
![image](https://github.com/NoNameGivenCoder/Sapphire/assets/68186230/4de4fe96-c1c7-44f3-acd6-ca90d44834f1)

**Comment by miiwhen** [comment]
euofbewiuogbe4wrerhgetrhjtrujeyrshwsr

**Comment by davidsosa2022** [comment]
> ![image](https://user-images.githubusercontent.com/68186230/280809800-4de4fe96-c1c7-44f3-acd6-ca90d44834f1.png)

autism

**Comment by cooolgamer** [comment]
Guys, this is github not twitter

**Comment by SomeonesGarbage** [comment]
@cooolgamer no
