### ISSUE TITLE
Not enough Justice - Civilization

### ISSUE THREAD

**Issue by davidsosa2022** [NoNameGivenCoder/Sapphire#11]
https://youtu.be/SVq2yMuAMVQ?si=YFyAivDVMTmh3O1-

This video needs to be on the Sapphire source code for no reason.

**Comment by SomeonesGarbage** [comment]
make it a pull request :trollface:

**Comment by imora7024** [comment]
...this is such a uselesss request. im sorry but this does nothing to the project.
